# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmsD1QGaLf-Rgre3rDysSjl2vi7ete88
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

r_min = 100
r_max = 200

img = cv2.imread("/content/ford.jpg", 0)

# Initialize slice_with_bg and slice_without_bg
slice_with_bg = img.copy() # Keeps original background for values outside range
slice_without_bg = np.zeros(img.shape, dtype=np.uint8) # All zeros initially, no background

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        pixel_value = img[i, j]
        if r_min <= pixel_value <= r_max:
            slice_with_bg[i, j] = 255 # Make pixels in range white in slice_with_bg
            slice_without_bg[i, j] = 255 # Make pixels in range white in slice_without_bg
        else:
            # For slice_with_bg, pixels outside the range retain their original values from img.copy()
            slice_without_bg[i, j] = 0 # Make pixels outside range black in slice_without_bg

# Display images
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(img, cmap='gray')
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(slice_with_bg, cmap='gray')
plt.title(f'Slice with BG ({r_min}-{r_max})')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(slice_without_bg, cmap='gray')
plt.title(f'Slice without BG ({r_min}-{r_max})')
plt.axis('off')

plt.show()